const theme = {
  mainColor: "#141414",
  subColor: "LightSteelBlue",
  formColor: "#f7f6f6",
  calendarTopColor: "LightGrey",
  calendarMidColor: "Gainsboro",
  calendarBottomColor: "Snow",
  placeholderColor: "MediumSeaGreen",
  textWaringColor: "tomato",
  navigationBGColor: "SteelBlue",
  backgroundTextColor: "MintCream",
  colorGainsboro: "Gainsboro",
  hoverColor: "teal",
  hoverCancleColor: "IndianRed",
  fontSizeBg: "1.3rem",
  fontWeightBg: 400,
  fontIconSize: "15px",
  signupInputLineHeight: "0.3rem",
  borderRadius: "4px",
  backgroundPaddingTop: "12vh",
  iphoneWidth: "100vw",
  webWidth: "425px",
};

export default theme;
