const theme = {
  //color
  mainColor: "#1c1c1c",
  subColor: "Gainsboro",
  formColor: "#f7f6f6",
  calendarTopColor: "LightGrey",
  calendarMidColor: "Gainsboro",
  calendarBottomColor: "Snow",
  placeholderColor: "MediumSeaGreen",
  textWaringColor: "tomato",
  backgroundTextColor: "MintCream",
  colorGainsboro: "Gainsboro",
  storyCardBgColor: "rgba(255, 250, 250, 0.55)",
  profileBorderColor: "ForestGreen",
  profileBorderHoverColor: "DodgerBlue",
  cardSelectColor: "rgba(30, 144, 255,0.5)",
  DarkSlateGrey: "DarkSlateGrey",
  btnBgColor: "rgba(248, 248, 255,0.45)",
  hoverColor: "rgba(72, 169, 153,0.75)",
  hoverCancleColor: "rgba(205, 92, 92,0.7)",
  navigationBGColor: "Silver",
  SideBarBgColor: "rgba(46, 139, 87, 0.45)",
  replyBgColor: "lightGray",
  //font
  fontSizeBg: "1.3rem",
  fontIconSize: "15px",
  fontWeightBg: 400,
  fontImgUploadIcon: "2rem",
  fontWritePageXLarge: "1.7rem",
  fontWritePageLarge: "1.5rem",
  fontWritePageMid: "1.3rem",
  fontWritePageSmall: "1.1rem",
  fontWritePageXSmall: "0.9rem",
  font1rem: "1rem",
  fontBtnMid: "1rem",
  fontBtnSmall: "0.9rem",
  fontToolTip: "0.8rem",
  fontDateSmall: "0.8rem",
  fontCalendarArrowBtn: "1.5rem",
  fontToggleIcon: "1.4rem",
  //layout
  signupInputLineHeight: "0.3rem",
  backgroundPaddingTop: "8vh",
  iphoneWidth: "100vw",
  webWidth: 410,
  //style
  borderRadius: "5px",
  backgroundImgHeight: "28vh",
  loadingPointerSize: "10px",
};

export default theme;
